# Site settings
title: Jonas Erthal
tagline: Computer Programmer
author: Jonas Erthal
email: erthaljonas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aspiring amateur of many things.

# Site URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jonaserthal.com" # Add your actual domain here
enforce_ssl: jonaserthal.com   # If you have SSL enabled

# Social media and professional profiles
social:
  twitter: apollopower
  github: apollopower
  linkedin: jonaserthal
  
twitter:
  username: apollopower
  card: summary_large_image

# Build settings
theme: minima
permalink: /:year/:month/:title/ # Clean URL structure for better SEO

# Important SEO plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Navigation
header_pages:
  - blog.markdown
  - games.markdown

# Custom footer
footer: 'Find me also on <a href="https://www.linkedin.com/in/jonaserthal/">LinkedIn</a>'

# Defaults for posts and pages
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Jonas Erthal
      image: /assets/images/default-post-image.jpg  # Add a default OG image
      comments: true

# SEO and Analytics (uncomment and add your IDs)
# google_analytics: UA-XXXXXXXX-X
# google_site_verification: [Your Google Search Console verification code]

# Compression and optimization
sass:
  style: compressed

# Keep the original exclude list
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/